<?php

namespace App\Services;

use App\Models\GoodsCustomer;
use App\Models\GoodsCustomerStatusHistory;
use App\Models\OutsideContact;
use App\Models\User;
use Illuminate\Support\Arr;

class OutsideWhatsappInboundService
{
    /**
     * @param  array<string, mixed>  $value  كائن value من webhook واتساب
     * @return array<string, string> رقم موحّد (أرقام فقط) => الاسم من الملف الشخصي
     */
    public function profileNamesByNormalizedPhone(array $value): array
    {
        $map = [];
        foreach (Arr::wrap(data_get($value, 'contacts', [])) as $row) {
            if (! is_array($row)) {
                continue;
            }
            $waId = (string) data_get($row, 'wa_id', '');
            $digits = preg_replace('/\D+/', '', $waId) ?: '';
            $name = trim((string) data_get($row, 'profile.name', ''));
            if ($digits !== '' && $name !== '') {
                $map[$digits] = mb_substr($name, 0, 255);
            }
        }

        return $map;
    }

    public function enrichOutsideContact(OutsideContact $contact, ?string $profileName): void
    {
        $profileTrim = $profileName !== null ? mb_substr(trim($profileName), 0, 255) : '';
        $dirty = false;

        if ($profileTrim !== '') {
            $current = trim((string) ($contact->name ?? ''));
            if ($current === '' || $this->nameLooksAutoGenerated($current)) {
                $contact->name = $profileTrim;
                $dirty = true;
            }

            $meta = array_merge($contact->meta ?? [], [
                'whatsapp_profile_name' => $profileTrim,
                'whatsapp_profile_captured_at' => now()->toIso8601String(),
            ]);
            $contact->meta = $meta;
            $dirty = true;
        }

        if ($dirty) {
            $contact->save();
        }
    }

    /**
     * بعد تخزين أول رسالة واردة جديدة: إنشاء عميل بضاعة مربوط بجهة الخارج إن لم يوجد.
     */
    public function ensureGoodsCustomerForNewInbound(
        OutsideContact $contact,
        ?string $profileName,
        string $messageBodyPreview
    ): void {
        if (data_get($contact->meta, 'employee_user_id')) {
            return;
        }

        if (GoodsCustomer::query()->where('outside_contact_id', $contact->id)->exists()) {
            return;
        }

        $phoneNorm = preg_replace('/\D+/', '', (string) $contact->phone) ?: (string) $contact->phone;

        $unlinked = GoodsCustomer::query()
            ->whereNull('outside_contact_id')
            ->whereNotNull('phone')
            ->get();

        foreach ($unlinked as $candidate) {
            $cPhone = preg_replace('/\D+/', '', (string) ($candidate->phone ?? '')) ?: '';
            if ($cPhone !== '' && $cPhone === $phoneNorm) {
                $candidate->update([
                    'outside_contact_id' => $contact->id,
                    'name' => $this->pickBetterCustomerName(
                        $profileName,
                        (string) $candidate->name,
                        (string) $candidate->phone
                    ),
                ]);

                return;
            }
        }

        $displayName = $this->resolveDisplayName($profileName, $contact, $messageBodyPreview);

        $ownerId = User::query()->where('role', 'admin')->orderBy('id')->value('id');

        $customer = GoodsCustomer::query()->create([
            'outside_contact_id' => $contact->id,
            'name' => $displayName,
            'phone' => $contact->phone,
            'company' => null,
            'status' => 'lead',
            'notes' => 'تسجيل تلقائي من أول رسالة واتساب (قسم الخارج → البضاعة).',
            'owner_user_id' => $ownerId,
            'confirmed_at' => null,
        ]);

        GoodsCustomerStatusHistory::query()->create([
            'goods_customer_id' => $customer->id,
            'from_status' => null,
            'to_status' => 'lead',
            'note' => 'إنشاء تلقائي عبر webhook واتساب',
            'user_id' => null,
        ]);
    }

    private function pickBetterCustomerName(?string $profileName, string $existingName, string $phoneForFallback): string
    {
        $p = $profileName !== null ? trim($profileName) : '';
        if ($p !== '') {
            return mb_substr($p, 0, 255);
        }

        $e = trim($existingName);
        if ($e !== '') {
            return mb_substr($e, 0, 255);
        }

        return $this->fallbackNameFromPhone($phoneForFallback);
    }

    private function nameLooksAutoGenerated(string $name): bool
    {
        return (bool) preg_match('/^(جهة|عميل)\s+\p{Nd}{2,8}$/u', trim($name));
    }

    private function resolveDisplayName(?string $profileName, OutsideContact $contact, string $preview): string
    {
        $fromProfile = $profileName !== null ? trim($profileName) : '';
        if ($fromProfile !== '') {
            return mb_substr($fromProfile, 0, 255);
        }

        $fromContact = trim((string) ($contact->name ?? ''));
        if ($fromContact !== '' && ! $this->nameLooksAutoGenerated($fromContact)) {
            return mb_substr($fromContact, 0, 255);
        }

        $normalizedPreview = str_replace(["\r\n", "\r"], "\n", $preview);
        $firstLine = trim((string) strtok($normalizedPreview, "\n"));
        if ($firstLine !== '' && mb_strlen($firstLine) >= 2 && mb_strlen($firstLine) <= 60) {
            if (! preg_match('/^\[[^\]]+]$/u', $firstLine)) {
                return mb_substr($firstLine, 0, 255);
            }
        }

        return $this->fallbackNameFromPhone((string) $contact->phone);
    }

    private function fallbackNameFromPhone(string $phone): string
    {
        $digits = preg_replace('/\D+/', '', $phone) ?: '';
        $suffix = mb_strlen($digits) >= 4 ? mb_substr($digits, -4) : ($digits !== '' ? $digits : '0000');

        return 'جهة '.$suffix;
    }
}
